### ISSUE TITLE
NPE when processing HTTP reponse

### ISSUE THREAD

**Issue by jaimecasero** [Mobicents/charging-server#4]
19:22:06,072 ERROR [CS-ABMF-NAKA] (SLEE-EventRouterExecutor-6-thread-1) [xx] Unable to parse HTTP Post Answer from Billing Server.
java.lang.NullPointerException
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:64)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:54)
	at org.mobicents.charging.server.account.naka.NakaAccountBalanceManagementSbb.onResponseEvent(NakaAccountBalanceManagementSbb.java:638)
	at sun.reflect.GeneratedMethodAccessor302.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mobicents.slee.runtime.sbbentity.SbbEntityImpl.invokeEventHandler(SbbEntityImpl.java:479)
	at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.routeQueuedEvent(EventRoutingTaskImpl.java:381)
	at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.run(EventRoutingTaskImpl.java:128)
	at org.mobicents.slee.runtime.eventrouter.EventRouterExecutorImpl$EventRoutingTaskStatsCollector.run(EventRouterExecutorImpl.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by nhanth87** [comment]
fixed in bitbucket, waiting for customer response
